baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Lewisia Farms'
theme = ''  # Leave this empty if you're not using a theme

[params]
  description = "Fresh, Local, Antibiotic-Free produce from the heart of the Bitterroot Valley"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4