baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Lewisia Farms'
theme = ''

[params]
  description = "Fresh, Local, Antibiotic-Free produce from the heart of the Bitterroot Valley"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"
# Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://lewisiafarms.com?region=us-west-2"